# Bevezetés {#Chapter-1}

```{css, echo=FALSE}
p {
text-align: justify;
  }
```

A születendő gyermekek száma olyan téma, amely számos politikai vita központjába kerül napjainkban. A vita alapját adja, hogy egyik oldalon a Föld eltartó képességére hivatkozva, vannak, akik azt tartják helyesnek, ha a népesség csökkentését sürgetjük, míg mások számos indokot állítanak fel ezzel szemben. A bruttó nemzeti kibocsátás jelentős része származhat pusztán a demográfiai növekedésből. Ha a kibocsátás növekedése főként a lélekszám növekedéséből származik, abban az esetben ez nem vezet az életszínvonal emelkedéséhez, az egy főre jutó jövedelem nem nő a népesség számának növekedésével, azonban globális politikai súlyként szolgál a nagyobb kibocsátás. Fontos indok lehet mögötte a számos országban működő felosztó-kirovó nyugdíjrendszer fenntarthatósága. Az elsőként említett állásponton lévő országra kiváló példa Kína, aki az egy gyermek politika bevezetésével a népességének csökkentését kívánja kiváltani. A szemben álló oldalra sorolható akár Magyarország is. Nem is olyan régen jelent meg a hazai médiában, hogy a magyar miniszterelnök “alkut kíván kötni a magyar nőkkel”, majd bejelentette a négy gyermekes családok adókedvezményét. A natalizmus^[A születési arányszám célként való kitűzése.] visszatérése nem újdonság, számos más európai ország üdvözli^[Az Európai Bizottság elnökének, Ursula von der Leyen twitter oldalának borítója is büszkén hirdeti: „hét gyermek édesanyja”.], annak európai történelme igen sötét képeket fest 21. századi szemmel (The Economist, 2020, b). Bármely oldalon is kíván egy ország vezetése helyet foglalni, az aktuális demográfiai folyamatokról szóló előrejelzések, illetőleg a folyamatot befolyásoló lehetséges eszközök, és a natalizmus gazdasági-társadalmi következményeinek ismerete elengedhetetlen.\
\
Ezen tanulmány során elemzést végzek a Magyarországot jellemző születési mutatók elmúlt félévszázad során végbemenő változásain, illetőlegek a témában ismert szakirodalom alapján relevánsnak tekinthető más gazdaság és társadalmi indikátorokkal való kapcsolatán. A dolgozat során az idősorelemzés általános eszközeit alkalmazom, köztük az Box-Jenkins eljárást, vektor-autoregresszív modelleket, illetőlegesen Granger-okság és kointegráció vizsgálatát végzem el. A fentebb felsorolt eszközök segítségével előrejelzést készítek a magyar termékenységi ráta várható alakulásával kapcsolatosan. Az oksági vizsgálatok során kapott eredményeknek az általános közgazdasági elméletekkel való megegyezésüknek, illetőlegesen hitelességüknek való alátámasztásuk érdekében további vizsgálódásokat végzek. Az általam végzett számítások R kódjai az alábbi weboldalon érhetőek el: https://github.com/MarcellGranat/fertility/blob/master/TDK-2020-fertility.R